// import { AuroraBackground } from "@/components/AuroraBackground";
import Footer from "@/components/Footer2";
import Navbar from "@/components/Navbar";
import { BackgroundBeams } from "@/components/ui/background-beams";

export const metadata = {
  title: "Login",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <div className="relative w-full bg-slate-100 dark:bg-slate-950 antialiased">
        <div className="relative z-40">
          <Navbar></Navbar>
          {children}
        </div>
        <BackgroundBeams className="" />
      </div>

      <Footer></Footer>
    </>
  );
}
