export const metadata = {
    title: "Forgot Password",
    description: "Generated by Next.js",
  };
  
  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode;
  }) {
    return <div>{children}</div>;
  }
  